website/events/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('', views.events_home, name='events_home'),
    # Events urls.
    path('eventos/', views.events_list, name='event_list'),
    path('eventos/<pk>/configuracion/', views.event_detail, name='event_detail'),
    path('eventos/<pk>/editar/', views.event_change, name='event_change'),
    path(
        'eventos/<pk>/agregar-categoria-sponsor/',
        views.event_create_sponsor_category,
        name='event_create_sponsor_category'
    ),
    path(
        'eventos/<pk>/descuentos-sponsor/crear/',
        views.event_create_sponsor_discount,
        name='event_create_sponsor_discount'
    ),

    # Sponsoring urls.
    path('eventos/<event_pk>/patrocinios/', views.sponsoring_list, name='sponsoring_list'),
    path(
        'eventos/<event_pk>/patrocinios/crear/',
        views.sponsoring_create,
        name='sponsoring_create'
    ),
    path(
        'eventos/patrocinios/<pk>/',
        views.sponsoring_detail,
        name='sponsoring_detail'
    ),

    path(
        'eventos/patrocinios/<pk>/cerrar',
        views.sponsoring_set_close,
        name='sponsoring_set_close'
    ),
    path(
        'eventos/patrocinios/<pk>/factura/crear/',
        views.sponsoring_invoice_create,
        name='sponsoring_invoice_create'
    ),

    path(
        'eventos/factura/<pk>/afectacion/crear/',
        views.sponsoring_invoice_affect_create,
        name='sponsoring_invoice_affect_create'
    ),

    # Expenses urls.
    path('eventos/<event_pk>/gastos/', views.expenses_list, name='expenses_list'),
    path(
        'eventos/<event_pk>/gastos/proveedor/crear/',
        views.provider_expense_create,
        name='provider_expense_create'
    ),
    path(
        'eventos/<event_pk>/gastos/organizador/crear/',
        views.organizer_refund_create,
        name='organizer_refund_create'
    ),
    path(
        'eventos/gasto_proveedor/<pk>/',
        views.provider_expense_detail,
        name='provider_expense_detail'
    ),
    path(
        'eventos/gasto_proveedor/<pk>/editar/',
        views.provider_expense_update,
        name='provider_expense_update'
    ),
    path(
        'eventos/gasto_proveedor/<pk>/switch/',
        views.provider_expense_switch_state,
        name='provider_expense_switch_state'
    ),
    path(
        'eventos/reintegro/<pk>/',
        views.organizer_refund_detail,
        name='organizer_refund_detail'
    ),
    path(
        'eventos/gasto_proveedor/<pk>/pago/crear/',
        views.provider_expense_payment_create,
        name='provider_expense_payment_create'
    ),
    path(
        'organizadores/<pk>/reintegros/pagar/',
        views.organizer_refund_payment_create,
        name='organizer_refund_payment_create'
    ),
    path(
        'organizadores/<pk>/reintegros/switch/',
        views.organizer_refund_switch_state,
        name='organizer_refund_switch_state'
    ),
    # Invoice actions urls.
    path(
        'eventos/factura/<pk>/aprobar/',
        views.invoice_set_approved,
        name='invoice_set_approved'
    ),
    path(
        'eventos/factura/<pk>/setear-pago-completo/',
        views.invoice_set_complete_payment,
        name='invoice_set_complete_payment'
    ),
    path(
        'eventos/factura/<pk>/setear-pago-parcial/',
        views.invoice_set_partial_payment,
        name='invoice_set_partial_payment'
    ),

    # Organizers urls.
    path('registrar-organizador/', views.organizer_signup, name='organizer_signup'),
    path('organizadores/', views.organizers_list, name='organizer_list'),
    path('organizadores/<pk>/', views.organizer_detail, name='organizer_detail'),
    path('organizadores/<pk>/editar/', views.organizer_change, name='organizer_change'),
    path(
        'organizadores/<pk>/agregar-cuenta-bancaria/',
        views.organizer_create_bank_account_data,
        name='organizer_create_bank_account_data'
    ),
    path(
        'cuenta-bancaria/<pk>/editar/',
        views.organizer_update_bank_account_data,
        name='organizer_update_bank_account_data'
    ),

    # Sponsors urls.
    path('patrocinadores/', views.sponsors_list, name='sponsor_list'),
    path('patrocinadores/crear/', views.sponsor_create, name='sponsor_create'),
    path('patrocinadores/<pk>/', views.sponsor_detail, name='sponsor_detail'),
    path('patrocinadores/<pk>/editar/', views.sponsor_change, name='sponsor_change'),
    path('patrocinadores/<pk>/habilitar/', views.sponsor_set_enabled, name='sponsor_set_enabled'),

    # Providers urls.
    path('proveedores/', views.providers_list, name='provider_list'),
    path('proveedores/crear/', views.provider_create, name='provider_create'),
    path('proveedores/<pk>/', views.provider_detail, name='provider_detail'),
    path('proveedores/<pk>/editar/', views.provider_change, name='provider_change'),

    # Others

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
    path('eventos/', include('events.urls')),
    path('cuentas/', include('pyar_auth.urls')),
]

website/events/helpers/models.py
# for local setup 
# before running this file on your local system follow the given commands in your terminal
# pip install django
# pip install django-extensions
from django.contrib.auth import get_user_model
from django.db import models
from django_extensions.db.models import TimeStampedModel
from events.middleware import get_current_user

from django.urls import reverse
Redirect_Variable = reverse()

User = get_user_model()


class AuditUserTime(TimeStampedModel):
    """Abstrac model to audith times and user."""
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='%(app_label)s_%(class)s_created_by'
    )

    changed_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='%(app_label)s_%(class)s_changed_by'
    )

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and user.is_authenticated:
            if not self.pk:  #: Is a create.
                self.created_by = user
            self.changed_by = user
        super(AuditUserTime, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class SaveReversionMixin:
    '''Mixin to override save, wrapping with create_revision.
    To better work keep on left on inheritance.'''
    def save(self, *args, **kwargs):
        with reverse.create_revision():
            super(SaveReversionMixin, self).save(*args, **kwargs)


class ActiveManager(models.Manager):
    '''Manager to show only active instances.'''
    def get_queryset(self):
        return super().get_queryset().filter(active=True)

website/members/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import TimeStampedModel
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.templatetags.static import static

DEFAULT_MAX_LEN = 317  # Almost random
LONG_MAX_LEN = 2048  # Random but bigger


class Quota(TimeStampedModel):
    """Like cuota in Spanish... exactly that. A monthly fee some member pays."""

    payment = models.ForeignKey('Payment', verbose_name=_('pago'), on_delete=models.CASCADE)
    month = models.PositiveSmallIntegerField(
        _('mes'), validators=[MaxValueValidator(12), MinValueValidator(1)])
    year = models.PositiveSmallIntegerField(_('año'), validators=[MinValueValidator(2015)])
    member = models.ForeignKey(
        'Member', verbose_name=_('miembro'), on_delete=models.SET_NULL, null=True)

    class Meta:
        get_latest_by = ['year', 'month']

    def __str__(self):
        return "<Quota {}-{} payment={}".format(self.year, self.month, self.payment)

    @property
    def code(self):
        return f'{self.year}-{self.month:02d}'

    @classmethod
    def decode(cls, code):
        return int(code[:2]), int(code[2:])

    @classmethod
    def code_from_date(cls, when):
        return when.strftime('%y%m')


class Member(TimeStampedModel):
    """Base Model for the Membership to the ONG. People and Organizations can be members."""

    legal_id = models.PositiveIntegerField(_('ID legal'), unique=True, blank=True, null=True)
    registration_date = models.DateField(_('fecha de alta'), blank=True, null=True)
    shutdown_date = models.DateField(_('fecha de baja'), blank=True, null=True)

    category = models.ForeignKey(
        'Category',
        verbose_name=_('categoría'),
        null=True,
        on_delete=models.SET_NULL,
        related_name='members'
    )
    patron = models.ForeignKey(  # This is the person that pays for this Member's subscription
        'Patron',
        verbose_name=_('mecenas'),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='beneficiary'
    )
    first_payment_month = models.PositiveSmallIntegerField(
        _('primer pago mes'), validators=[MaxValueValidator(12), MinValueValidator(1)],
        null=True, blank=True)
    first_payment_year = models.PositiveSmallIntegerField(
        _('primer pago año'), validators=[MinValueValidator(2015)], null=True, blank=True)

    # Flags
    has_student_certificate = models.BooleanField(
        _('tiene certificado de estudiante?'), default=False)
    has_subscription_letter = models.BooleanField(_('ha firmado la carta?'), default=False)
    has_collaborator_acceptance = models.BooleanField(
        _('ha aceptado ser colaborador?'), default=False)

    @property
    def entity(self):
        """Return the Person or Organization for the member, if any."""
        try:
            return self.person
        except Person.DoesNotExist:
            pass

        try:
            return self.organization
        except Organization.DoesNotExist:
            pass

    def __str__(self):
        legal_id = "∅" if self.legal_id is None else f'{self.legal_id:05d}'
        shutdown = "" if self.shutdown_date is None else ", DADO DE BAJA"
        return f"{legal_id} - [{self.category}{shutdown}] {self.entity}"

    def get_missing_info(self, for_approval=False):
        """Indicate in which categories the member is missing something.

        If `for_approval` is indicated, some data will not be reported as missing (as they
        are not really needed for legal approval).
        """
        cat_student = Category.objects.get(name=Category.STUDENT)
        cat_collab = Category.objects.get(name=Category.COLLABORATOR)

        # simple flags with "Not Applicable" situation
        missing_student_certif = (
            self.category == cat_student and not self.has_student_certificate)
        missing_collab_accept = (
            self.category == cat_collab and not self.has_collaborator_acceptance)

        # info from Person
        missing_nickname = self.person.nickname == ""
        # picture is complicated, bool() is used to check if the Image field has an associated
        # filename, and False itself is used as the "dont want a picture!" flag
        missing_picture = not self.person.picture and self.person.picture is not False

        # info from Member itself
        missing_payment = self.first_payment_month is None and self.category.fee > 0
        missing_signed_letter = not self.has_subscription_letter

        # some fields are not really needed to for a member to be legally approved
        if for_approval:
            missing_nickname = False
            missing_picture = False
            missing_payment = False

        return {
            'missing_signed_letter': missing_signed_letter,
            'missing_student_certif': missing_student_certif,
            'missing_payment': missing_payment,
            'missing_nickname': missing_nickname,
            'missing_picture': missing_picture,
            'missing_collab_accept': missing_collab_accept,
        }


def picture_upload_path(instance, filename):
    """Customize the picture's upload path to MEDIA_ROOT/pictures/lastname_document.ext."""
    ext = filename.split('.')[-1]
    lastname = instance.last_name.lower().replace(' ', '')
    return f"pictures/{lastname}_{instance.document_number}.{ext}"


def validate_image_ratio(obj):
    width, height = get_image_dimensions(obj)
    if width != height:
        raise ValidationError("Por favor, utilice una imagen cuadrada")


class Person(TimeStampedModel):
    """Human being, member of PyAr ONG."""

    first_name = models.CharField(_('nombre'), max_length=DEFAULT_MAX_LEN)
    last_name = models.CharField(_('apellido'), max_length=DEFAULT_MAX_LEN)

    membership = models.OneToOneField(
        'Member',
        verbose_name=_('membresía'),
        related_name='person',
        on_delete=models.CASCADE,
    )

    document_number = models.CharField(
        _('N° de documento'), max_length=DEFAULT_MAX_LEN, null=False, unique=True)
    email = models.EmailField(_('correo electrónico'), max_length=1024)
    nickname = models.CharField(
        _('nick'), max_length=DEFAULT_MAX_LEN, blank=True, help_text=_('Nick o sobrenombre'))
    # picture in "False" means that the person doesn't want a photo (can not use Null as it's
    # swallowed by ImageField to disassociate from a filename)
    picture = models.ImageField(
        _('avatar'), validators=[validate_image_ratio], upload_to=picture_upload_path,
        null=True, blank=True, help_text=_('Foto o imagen cuadrada para el carnet'))
    nationality = models.CharField(_('nacionalidad'), max_length=DEFAULT_MAX_LEN, blank=True)
    marital_status = models.CharField(_('estado civil'), max_length=DEFAULT_MAX_LEN, blank=True)
    occupation = models.CharField(
        _('profesión'), max_length=DEFAULT_MAX_LEN, blank=True,
        help_text=_('Profesión o ocupación'))
    birth_date = models.DateField(_('fecha de nacimiento'), null=True, blank=True)
    street_address = models.CharField(_('dirección'), max_length=DEFAULT_MAX_LEN, blank=True)
    zip_code = models.CharField(_('código postal'), max_length=DEFAULT_MAX_LEN, blank=True)
    city = models.CharField(_('ciudad'), max_length=DEFAULT_MAX_LEN, blank=True)
    province = models.CharField(_('provincia'), max_length=DEFAULT_MAX_LEN, blank=True)
    country = models.CharField(_('país'), max_length=DEFAULT_MAX_LEN, blank=True)

    comments = models.TextField(_('comentarios'), blank=True)

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def address(self):
        return f"{self.street_address}, {self.city} ({self.zip_code}), {self.province}"

    @property
    def thumbnail(self):
        if self.picture:
            photo = self.picture.url
        else:
            photo = static("images/default_thumbnail.jpg")
        return format_html(
            f'<a href="{photo}"><img src="{photo}" \
                    class="img-thumbnail" width="150"></a>')

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class Organization(TimeStampedModel):
    """Organization (legal), member of the ONG."""
    name = models.CharField(_('nombre'), max_length=DEFAULT_MAX_LEN, blank=True)
    contact_info = models.TextField(_('información de contacto'), blank=True)
    document_number = models.CharField(_('CUIT'), max_length=DEFAULT_MAX_LEN, blank=True,
                                       help_text='CUIT o equivalencia')

    membership = models.OneToOneField(
        'Member',
        verbose_name=_('membresía'),
        null=True,
        on_delete=models.SET_NULL,
        related_name='organization'
    )

    address = models.CharField(_('dirección'), max_length=LONG_MAX_LEN, blank=True)
    social_media = models.TextField(_('redes sociales'), blank=True)

    def __str__(self):
        return self.name


class Category(TimeStampedModel):
    """Membership category."""
    ACTIVE = "Activo"
    SUPPORTER = "Adherente"
    STUDENT = "Estudiante"
    COLLABORATOR = "Colaborador"
    TEENAGER = "Cadete"
    BENEFACTOR_PLATINUM = "Benefactora Platino"
    BENEFACTOR_GOLD = "Benefactora Oro"
    BENEFACTOR_SILVER = "Benefactora Plata"
    CATEGORY_CHOICES = (
        (ACTIVE, ACTIVE),
        (SUPPORTER, SUPPORTER),
        (STUDENT, STUDENT),
        (COLLABORATOR, COLLABORATOR),
        (TEENAGER, TEENAGER),
        (BENEFACTOR_PLATINUM, BENEFACTOR_PLATINUM),
        (BENEFACTOR_GOLD, BENEFACTOR_GOLD),
        (BENEFACTOR_SILVER, BENEFACTOR_SILVER),
    )
    HUMAN_CATEGORIES = {ACTIVE, SUPPORTER, STUDENT, COLLABORATOR, TEENAGER}

    class Meta:

website/events/helpers/views.py
from django.db.models import Q
import functools
import operator


def search_filtered_queryset(base_queryset, search_fields, search_value):
    filters = []
    for key, value in search_fields.items():
        field_filter = key
        if value != 'equal':
            field_filter = field_filter + '__' + value
        filter_dict = {field_filter: search_value}
        filters.append(Q(**filter_dict))
    queryset = base_queryset.filter(functools.reduce(operator.or_, filters))
    return queryset

website/events/templates/events/expenses/expenses_list.html
{% extends "events_base_paginated_list.html" %}
{% load humanize %}
{% block route-navigator %}
<nav aria-label="breadcrumb" class="events-details-nav">
    <div>
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><i class="fas fa-home"></i><a href="{% url 'events_home' %}"> Inicio</a></li>
        <li class="breadcrumb-item"><i class="fas fa-calendar-alt"></i><a href="{% url 'event_list' %}"> Eventos</a></li>
        <li class="breadcrumb-item"><i class="fas fa-calendar-check"></i><a href="{% url 'event_detail' pk=event.pk %}"> {{event.name}}</a></li>
        <li class="breadcrumb-item" aria-current="page"><i class="fas fa-hand-holding-usd"></i> Gastos</li>
        </ol>
    </div>
    <div>
        Ir a:  
        <i class="fa fa-cog"></i> 
        <a title="editar evento" href="{% url 'event_detail' pk=event.pk %}">
            General
        </a>
        |
        <i class="fas fa-handshake"></i><a title="administrar evento" href="{% url 'sponsoring_list' event_pk=event.pk %}">
            Sponsoreos
        </a>
    </div>
</nav>
{% endblock %}

{% block list_title %}
<h1>Gastos</h1><h3>{{event}}</h3>

{%endblock%}

{% block list_content %}
    <div class="row expenses-list">
        <div class="col-md-12">
            <table class="table table-striped row-clickeable-table">
                <thead>
                    <tr>
                        <th scope="row">Tipo</th>
                        <th scope="row">Origen</th>
                        <th scope="row">Monto</th>
                        <th scope="row">Descripción</th>
                        <th class="text-center" scope="row">Pagado</th>
                    </tr>
                </thead>
                <tbody>
                {% for expense in expenses_list %}
                    {% if expense.category == "Prv" %}
                    <tr onclick="window.location='{% url 'provider_expense_detail' pk=expense.pk %}';" class="clikeable">
                    {% else %}
                    <tr onclick="window.location='{% url 'organizer_refund_detail' pk=expense.pk %}';" class="clikeable">
                    {% endif %}
                    {% if expense.is_cancelled %}
                        <td class="text-danger">{{ expense.get_category_display }} (Cancelado)</td>
                    {% else %}
                        <td>{{ expense.get_category_display }}</td>
                    {% endif %}
                        <td>
                        {% if expense.category == "Prv"%}
                            {{ expense.origin.organization_name }}
                        {% else %}
                            {{ expense.origin.user.username }}
                        {% endif %}
                        </td>
                        <td>${{ expense.amount|intcomma }}</td>
                        <td>{{ expense.description }}</td>
                        <td class="text-center">
                            <span>
                            {% if expense.is_cancelled %}
                                <i class="fa fa-ban text-danger"></i>
                            {% elif expense.payment %}
                                <i class="fa fa-check-circle text-success"></i>
                            {% else %}
                                <i class="fa fa-times-circle text-danger"></i>
                            {% endif %}
                            </span>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="100%" class="empty-list">
                            <strong>No hay gastos cargados.</strong>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row sponsors-list-actions">
        <div class="col-md-12 text-right">
            {% if perms.events.add_providerexpense %}
            <a class="btn btn-primary float-right col-3 mx-1" href="{% url 'provider_expense_create' event_pk=event.pk %}"><i class="fas fa-money-bill-wave-alt"></i> Pago Proveedor</a>
            {% endif %}
            {% if perms.events.add_organizerrefund %}
            <a class="btn btn-info float-right col-3 mx-1" href="{% url 'organizer_refund_create' event_pk=event.pk %}"><i class="fas fa-wallet"></i> Reintegro</a>
            {% endif %}
            <a class="btn btn-danger col-3 float-right mx-1" href="{{request.META.HTTP_REFERER}}"><i class="fas fa-undo"></i> Volver</a>
        </div>
    </div>

{% endblock %}

website/events/templates/events/expenses/organizer_refund_detail.html
{% extends "events_base.html" %}
{% load humanize%}
{% load static %}
{% block content %}
<div class="container">
    {% block route-navigator %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><i class="fas fa-home"></i><a href="{% url 'events_home' %}"> Inicio</a></li>
          <li class="breadcrumb-item"><i class="fas fa-calendar-alt"></i><a href="{% url 'event_list' %}"> Eventos</a></li>
          <li class="breadcrumb-item"><i class="fas fa-calendar-check"></i><a href="{% url 'event_detail' pk=event.pk %}"> {{event.name}}</a></li>
          <li class="breadcrumb-item"><i class="fas fa-hand-holding-usd"></i><a href="{% url 'expenses_list' event_pk=event.pk %}"> Gastos</a></li>
          <li class="breadcrumb-item" aria-current="page"><i class="fas fa-wallet"></i> Reintegro Organizador ({{organizerrefund.pk}})</li>
        </ol>
    </nav>
    {% endblock %}
    <h2>Gasto Organizador</h2>
    <div class="row my-2">
        <!-- FACTURA -->
        <div class="col-md-6">
            <h4>Factura</h4>
            <div class="table-responsive">
                <table class="table table-sm table-bordered table-striped table-hover">
                    <tr>
                        <th scope="row">Organizador</th>
                        <td>{{organizerrefund.organizer.user.username}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Tipo</th>
                        <td>{{organizerrefund.get_invoice_type_display}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Monto</th>
                        <td>${{organizerrefund.amount|intcomma}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Fecha</th>
                        <td>{{organizerrefund.invoice_date}}</td>
                    </tr>
                    {% if organizerrefund.invoice %}
                    <tr>
                        <th>Documento</th>
                        <td><a href="{{organizerrefund.invoice.url}}" target="_blank" download><i class="fa fa-download"></i> descargar</a></td>
                    </tr>
                    {% endif %}
                </table>
            </div>
            {% if organizerrefund.invoice %}
            <div class="text-center">
                {% if organizerrefund.invoice_extension == ".pdf" %}
                <div id="invoice-pdf-div" invoice-url={{organizerrefund.invoice.url}}>
                    <a href="{{organizerrefund.invoice.url}}" target="_blank">
                        <canvas class="rounded border border-dark" id="pdf-canvas"></canvas>
                    </a>
                </div>
                {% elif organizerrefund.is_image_document %}
                <a href="{{organizerrefund.invoice.url}}" target="_blank">
                    <img class="rounded border border-dark" src="{{organizerrefund.invoice.url}}" style="width: 400px;">
                </a>
                {% else %}
                <a href="{{organizerrefund.invoice.url}}" target="_blank">
                    <img class="rounded border border-dark" src="{% static 'images/not_document.svg' %}" style="width: 400px;">
                </a>
                {% endif %}
            </div>
            {% endif %}
        </div>
        <!-- DESCRIPCIÓN -->
        <div class="col-md-6">
            <h4>Descripción</h4>
            <div class="rounded alet alert-primary p-3 my-2" role="alert">
            {% if organizerrefund.description %}
                <i class="fas fa-info-circle"></i> {{ organizerrefund.description }}
            {% else %}
                <span class="text-warning">
                    <i class="fas fa-exclamation-circle"></i> Gasto sin descripción adjunta
                </span>
            {% endif %}
            </div>
            {% if perms.events.change_organizerrefund and not organizerrefund.payment%}
            <!-- BUTTONS -->
            <div class="text-right">
                <button class="btn btn-warning" data-toggle="modal" data-target="#OrganizerRefundSwitchState">
                {% if organizerrefund.is_cancelled %}
                    <i class="fa fa-check"></i> Restaurar Gasto
                {% else %}
                <i class="fas fa-times-circle"></i> Cancelar Gasto
                {% endif %}
                </button>
            </div>
            <!-- OrganizerRefundSwitchState Modal -->
            <div class="modal fade" id="OrganizerRefundSwitchState" tabindex="-1" aria-labelledby="OrganizerRefundSwitchStateLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="OrganizerRefundSwitchStateLabel">
                                {% if organizerrefund.is_cancelled %}
                                <i class="fa fa-check"></i> Restaurar Gasto
                                {% else %}
                                <i class="fas fa-times-circle"></i> Cancelar Gasto
                                {% endif %}
                            </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form role="form" action="{% url 'organizer_refund_switch_state' organizerrefund.pk %}?next={% url 'organizer_refund_detail' pk=organizerrefund.pk %}" method="POST">
                            {% csrf_token %}
                            {% if organizerrefund.is_cancelled %}
                                ¿Está seguro que desea Restaurar el Gasto?
                            {% else %}
                                ¿Está seguro que desea Cancelar el Gasto?
                            {% endif %}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger float-right col-3 mx-1" data-dismiss="modal" aria-label="Close">
                                <i class="fas fa-times"></i> Cancelar
                            </button>
                            <button type="submit" class="btn btn-success float-right col-3 mx-1">
                                {% if organizerrefund.is_cancelled %}
                                <i class="fa fa-check"></i> Restaurar Gasto
                                {% else %}
                                <i class="fas fa-times-circle"></i> Cancelar Gasto
                                {% endif %}
                            </button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- End of Modal -->
            {% endif %}
            <h4>Comprobante Pago</h4>
            {% if organizerrefund.payment %}
            <div class="row">
                <div class="col-md-12 text-center">
                {% if organizerrefund.payment.extension == ".pdf" %}
                    <div id="pdf-payment" payment-url={{organizerrefund.payment.document.url}}>
                        <a href="{{organizerrefund.payment.document.url}}" target="_blank">
                            <canvas class="rounded border border-dark"></canvas>
                        </a>
                    </div>
                {% elif organizerrefund.payment.is_image_document %}
                    <div class="img-payment" payment-url={{organizerrefund.payment.document.url}}>
                        <a href="{{organizerrefund.payment.document.url}}" target="_blank">
                            <img class="rounded border border-dark" src="{{organizerrefund.payment.document.url}}" style="width: 200px;">
                        </a>
                    </div>
                {% else %}
                    <div payment-url={{organizerrefund.payment.document.url}}>
                        <a href="{{organizerrefund.payment.document.url}}" target="_blank">
                            <img class="rounded border border-dark" src="{% static 'images/not_document.svg' %}" style="width: 200px;">
                        </a>
                    </div>
                {% endif %}
                </div>
                <div class="col-md-12 text-center">
                    <a href="{{organizerrefund.payment.document.url}}" target="_blank" download><i class="fa fa-download"></i> descargar</a>
                </div>
            </div>
            {% else %}
            <div class="col-12 rounded alert alert-info" role="alert">
                Sin comprobantes de pago.
            </div>
            {% if perms.events.add_payment %}
            <div class="text-right">
                <a class="btn btn-primary float-right" href="{% url 'organizer_refund_payment_create' pk=organizerrefund.organizer.pk %}?next={% url 'organizer_refund_detail' pk=organizerrefund.pk %}"><i class="fa fa-plus"></i> Comprobante de pago</a>
            </div>
            {% endif %}
        {% endif %}
            </div>
        </div>
    <a class="btn btn-danger col-2 float-right mx-1" href="{{request.META.HTTP_REFERER}}"><i class="fas fa-undo"></i> Volver</a>
</div>
{% endblock %}

{% block extra_js %}
    <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
    <script src="{% static 'js/load_pdf_files.js' %}"></script>
{% endblock %}