website/events/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('', views.events_home, name='events_home'),
    # Events urls.
    path('eventos/', views.events_list, name='event_list'),
    path('eventos/<pk>/configuracion/', views.event_detail, name='event_detail'),
    path('eventos/<pk>/editar/', views.event_change, name='event_change'),
    path(
        'eventos/<pk>/agregar-categoria-sponsor/',
        views.event_create_sponsor_category,
        name='event_create_sponsor_category'
    ),
    path(
        'eventos/<pk>/descuentos-sponsor/crear/',
        views.event_create_sponsor_discount,
        name='event_create_sponsor_discount'
    ),

    # Sponsoring urls.
    path('eventos/<event_pk>/patrocinios/', views.sponsoring_list, name='sponsoring_list'),
    path(
        'eventos/<event_pk>/patrocinios/crear/',
        views.sponsoring_create,
        name='sponsoring_create'
    ),
    path(
        'eventos/patrocinios/<pk>/',
        views.sponsoring_detail,
        name='sponsoring_detail'
    ),

    path(
        'eventos/patrocinios/<pk>/cerrar',
        views.sponsoring_set_close,
        name='sponsoring_set_close'
    ),
    path(
        'eventos/patrocinios/<pk>/factura/crear/',
        views.sponsoring_invoice_create,
        name='sponsoring_invoice_create'
    ),

    path(
        'eventos/factura/<pk>/afectacion/crear/',
        views.sponsoring_invoice_affect_create,
        name='sponsoring_invoice_affect_create'
    ),

    # Expenses urls.
    path('eventos/<event_pk>/gastos/', views.expenses_list, name='expenses_list'),
    path(
        'eventos/<event_pk>/gastos/proveedor/crear/',
        views.provider_expense_create,
        name='provider_expense_create'
    ),
    path(
        'eventos/<event_pk>/gastos/organizador/crear/',
        views.organizer_refund_create,
        name='organizer_refund_create'
    ),
    path(
        'eventos/gasto_proveedor/<pk>/',
        views.provider_expense_detail,
        name='provider_expense_detail'
    ),
    path(
        'eventos/gasto_proveedor/<pk>/editar/',
        views.provider_expense_update,
        name='provider_expense_update'
    ),
    path(
        'eventos/gasto_proveedor/<pk>/switch/',
        views.provider_expense_switch_state,
        name='provider_expense_switch_state'
    ),
    path(
        'eventos/reintegro/<pk>/',
        views.organizer_refund_detail,
        name='organizer_refund_detail'
    ),
    path(
        'eventos/gasto_proveedor/<pk>/pago/crear/',
        views.provider_expense_payment_create,
        name='provider_expense_payment_create'
    ),
    path(
        'organizadores/<pk>/reintegros/pagar/',
        views.organizer_refund_payment_create,
        name='organizer_refund_payment_create'
    ),
    path(
        'organizadores/<pk>/reintegros/switch/',
        views.organizer_refund_switch_state,
        name='organizer_refund_switch_state'
    ),
    # Invoice actions urls.
    path(
        'eventos/factura/<pk>/aprobar/',
        views.invoice_set_approved,
        name='invoice_set_approved'
    ),
    path(
        'eventos/factura/<pk>/setear-pago-completo/',
        views.invoice_set_complete_payment,
        name='invoice_set_complete_payment'
    ),
    path(
        'eventos/factura/<pk>/setear-pago-parcial/',
        views.invoice_set_partial_payment,
        name='invoice_set_partial_payment'
    ),

    # Organizers urls.
    path('registrar-organizador/', views.organizer_signup, name='organizer_signup'),
    path('organizadores/', views.organizers_list, name='organizer_list'),
    path('organizadores/<pk>/', views.organizer_detail, name='organizer_detail'),
    path('organizadores/<pk>/editar/', views.organizer_change, name='organizer_change'),
    path(
        'organizadores/<pk>/agregar-cuenta-bancaria/',
        views.organizer_create_bank_account_data,
        name='organizer_create_bank_account_data'
    ),
    path(
        'cuenta-bancaria/<pk>/editar/',
        views.organizer_update_bank_account_data,
        name='organizer_update_bank_account_data'
    ),

    # Sponsors urls.
    path('patrocinadores/', views.sponsors_list, name='sponsor_list'),
    path('patrocinadores/crear/', views.sponsor_create, name='sponsor_create'),
    path('patrocinadores/<pk>/', views.sponsor_detail, name='sponsor_detail'),
    path('patrocinadores/<pk>/editar/', views.sponsor_change, name='sponsor_change'),
    path('patrocinadores/<pk>/habilitar/', views.sponsor_set_enabled, name='sponsor_set_enabled'),

    # Providers urls.
    path('proveedores/', views.providers_list, name='provider_list'),
    path('proveedores/crear/', views.provider_create, name='provider_create'),
    path('proveedores/<pk>/', views.provider_detail, name='provider_detail'),
    path('proveedores/<pk>/editar/', views.provider_change, name='provider_change'),

    # Others

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
    path('eventos/', include('events.urls')),
    path('cuentas/', include('pyar_auth.urls')),
]

website/events/helpers/models.py
# for local setup 
# before running this file on your local system follow the given commands in your terminal
# pip install django
# pip install django-extensions
from django.contrib.auth import get_user_model
from django.db import models
from django_extensions.db.models import TimeStampedModel
from events.middleware import get_current_user

from django.urls import reverse
Redirect_Variable = reverse()

User = get_user_model()


class AuditUserTime(TimeStampedModel):
    """Abstrac model to audith times and user."""
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='%(app_label)s_%(class)s_created_by'
    )

    changed_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='%(app_label)s_%(class)s_changed_by'
    )

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and user.is_authenticated:
            if not self.pk:  #: Is a create.
                self.created_by = user
            self.changed_by = user
        super(AuditUserTime, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class SaveReversionMixin:
    '''Mixin to override save, wrapping with create_revision.
    To better work keep on left on inheritance.'''
    def save(self, *args, **kwargs):
        with reverse.create_revision():
            super(SaveReversionMixin, self).save(*args, **kwargs)


class ActiveManager(models.Manager):
    '''Manager to show only active instances.'''
    def get_queryset(self):
        return super().get_queryset().filter(active=True)

website/events/models.py
import os
import stdnum
import reversion

from stdnum.exceptions import InvalidChecksum, InvalidLength, InvalidFormat, InvalidComponent
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from events.helpers.models import AuditUserTime, SaveReversionMixin, ActiveManager
from events.constants import (
    CAN_CLOSE_SPONSORING_CODENAME,
    CAN_SET_APPROVED_INVOICE_CODENAME,
    CAN_SET_COMPLETE_PAYMENT_CODENAME,
    CAN_SET_PARTIAL_PAYMENT_CODENAME,
    CAN_SET_SPONSORS_ENABLED_CODENAME,
    CAN_VIEW_EVENT_ORGANIZERS_CODENAME,
    CAN_VIEW_EXPENSES_CODENAME,
    CAN_VIEW_ORGANIZERS_CODENAME,
    CAN_VIEW_SPONSORS_CODENAME,
    CAN_VIEW_PROVIDERS_CODENAME,
    IMAGE_FORMATS,
    SPONSOR_STATE_CHECKED,
    SPONSOR_STATE_CLOSED,
    SPONSOR_STATE_COMPLETELY_PAID,
    SPONSOR_STATE_INVOICED,
    SPONSOR_STATE_PARTIALLY_PAID,
    SPONSOR_STATE_UNBILLED
)

from members.models import DEFAULT_MAX_LEN, LONG_MAX_LEN


User = get_user_model()
validation_module = stdnum.get_cc_module('ar', 'cbu')


def validate_cuit(cuit_to_validate):
    try:
        validator = stdnum.get_cc_module('ar', 'cuit')
        return validator.validate(cuit_to_validate)
    except (InvalidChecksum, InvalidFormat, InvalidComponent):
        raise ValidationError(
            _('El CUIT ingresado no es correcto')
        )
    except InvalidLength as err:
        raise ValidationError(
            _(str(err))
        )


def lower_non_spaces(text):
    return text.lower().replace(' ', '')


@reversion.register
class BankAccountData(SaveReversionMixin, AuditUserTime):
    """Account data for monetary transferences."""
    CC = 'CC'
    CA = 'CA'
    ACCOUNT_TYPE_CHOICES = (
        (CC, 'Cuenta corriente'),
        (CA, 'Caja de ahorros')
    )
    document_number = models.CharField(
        _('CUIT'),
        max_length=13,
        help_text=_('CUIT del propietario de la cuenta.'),
        validators=[validate_cuit]
    )

    bank_entity = models.CharField(
        _('entidad bancaria'),
        max_length=DEFAULT_MAX_LEN,
        help_text=_('Nombre de la entiedad bancaria.')
    )
    account_number = models.CharField(
        _('número de cuenta'),
        max_length=20,
        help_text=_('Número de cuenta.')
    )
    account_type = models.CharField(_('Tipo cuenta'), max_length=3, choices=ACCOUNT_TYPE_CHOICES)

    organization_name = models.CharField(
        _('razón social'),
        max_length=DEFAULT_MAX_LEN,
        help_text=_('Razón social o nombre del propietario de la cuenta.')
    )
    cbu = models.CharField(
        _('CBU'),
        max_length=DEFAULT_MAX_LEN,
        help_text=_('CBU de la cuenta'),
        validators=[validation_module.validate],
        blank=True
    )

    def is_owner(self, organizer):
        '''Returns if the organizer is the owner of the current account.'''
        return organizer in self.organizer_set.all()


@reversion.register
class Organizer(SaveReversionMixin, AuditUserTime):
    """Organizer, person asigned to administrate events."""
    first_name = models.CharField(_('nombre'), max_length=DEFAULT_MAX_LEN)
    last_name = models.CharField(_('apellido'), max_length=DEFAULT_MAX_LEN)

    user = models.OneToOneField(
        User,
        verbose_name=_('usuario'),
        on_delete=models.CASCADE
    )

    account_data = models.ForeignKey(
        'BankAccountData',
        verbose_name=_('datos cuenta bancaria'),
        on_delete=models.CASCADE,
        null=True
    )

    @property
    def email(self):
        return self.user.email

    def __str__(self):
        return f"{ self.user.username } - {self.email}"

    def get_associate_events(self, show_closed=False):
        if show_closed:
            return self.events
        else:
            return self.events.filter(close=False)

    def get_absolute_url(self):
        return reverse('organizer_detail', args=[str(self.pk)])

    def has_account_data(self):
        return self.account_data is not None

    def has_complete_personal_data(self):
        if self.first_name and self.last_name:
            return True
        else:
            return False

    def has_unpayment_refunds(self):
        return OrganizerRefund.objects.filter(organizer=self, payment__isnull=True).exists()

    class Meta:
        permissions = (
            (CAN_VIEW_ORGANIZERS_CODENAME, _('puede ver organizadores')),
        )
        ordering = ['-created']


@reversion.register
class Event(SaveReversionMixin, AuditUserTime):
    """A representation of an Event."""
    PYDAY = 'PD'
    PYCON = 'PCo'
    PYCAMP = 'PCa'
    PYCONF = 'Con'
    TYPE_CHOICES = (
        (PYDAY, 'PyDay'),
        (PYCON, 'PyCon'),
        (PYCAMP, 'PyCamp'),
        (PYCONF, 'Conferencia')
    )
    name = models.CharField(_('nombre'), max_length=DEFAULT_MAX_LEN)

    commission = models.DecimalField(
        _('comisión'),
        max_digits=5,
        decimal_places=2,
        validators=[MaxValueValidator(100), MinValueValidator(0)]
    )

    start_date = models.DateField(_('fecha de incio'), blank=True, null=True)
    place = models.CharField(_('lugar'), max_length=DEFAULT_MAX_LEN, blank=True)
    category = models.CharField(
        _('tipo'), max_length=3, choices=TYPE_CHOICES, blank=True)

    organizers = models.ManyToManyField(
        'Organizer',
        through='EventOrganizer',
        verbose_name=_('organizadores'),
        related_name='events'
    )

    close = models.BooleanField(_('cerrado'), default=False)

    def get_absolute_url(self):
        return reverse('event_detail', args=[str(self.pk)])

    def __str__(self):
        return (
            f"{self.get_category_display()} "
            f"- {self.name} "
            f"({self.place})"
        )

    def has_complete_data(self):
        return self.place and self.start_date and self.category

    class Meta:
        permissions = (
            (CAN_VIEW_EVENT_ORGANIZERS_CODENAME, _('puede ver organizadores del evento')),
        )
        ordering = ['-start_date']


@reversion.register
class EventOrganizer(SaveReversionMixin, AuditUserTime):
    """Represents the many to many relationship between events and organizers. With TimeStamped
    is easy to kwon when a user start as organizer from an event, etc."""
    event = models.ForeignKey('Event', related_name='event_organizers', on_delete=models.CASCADE)
    organizer = models.ForeignKey(
        'Organizer',
        related_name='organizer_events',
        on_delete=models.CASCADE
    )

    class Meta:
        unique_together = ('event', 'organizer')


@reversion.register
class SponsorCategory(SaveReversionMixin, AuditUserTime):
    name = models.CharField(_('nombre'), max_length=DEFAULT_MAX_LEN)
    amount = models.DecimalField(_('monto'), max_digits=18, decimal_places=2)
    event = models.ForeignKey(
        'Event',
        verbose_name=_('Evento'),
        on_delete=models.CASCADE,
        related_name='sponsors_categories'
    )

    sponsors = models.ManyToManyField(
        'Sponsor',
        through='Sponsoring',
        verbose_name=_('patrocinios'),
        related_name='sponsor_categories'
    )

    def __str__(self):
        return f"{self.event.name} ( {self.name} )"

    class Meta:
        unique_together = ('event', 'name')


@reversion.register
class Sponsoring(SaveReversionMixin, AuditUserTime):
    """
    Sponsoring:
    Represents the many to many relationship between SponsorCategory and Sponsors. Is important
    had this relation as model to payment fks, etc."""
    sponsorcategory = models.ForeignKey(
        'SponsorCategory',
        related_name='sponsor_by',
        on_delete=models.CASCADE,
        verbose_name=_('categoría'),
    )
    sponsor = models.ForeignKey(
        'Sponsor',
        related_name='sponsoring',
        on_delete=models.CASCADE,
    )
    comments = models.TextField(_('comentarios'), blank=True)
    close = models.BooleanField(_('cerrado'), default=False)

    def __str__(self):
        return (
            f"{self.sponsor.organization_name} "
            f"- {self.sponsorcategory.event.name} "
            f"({self.sponsorcategory.name})"
        )

    def get_absolute_url(self):
        return reverse('sponsoring_detail', args=[str(self.pk)])

    @property
    def state(self):
        # TODO: to not use so many "if" can write a decision matriz.
        current_state = SPONSOR_STATE_UNBILLED
        if self.close:
            return SPONSOR_STATE_CLOSED

        if hasattr(self, 'invoice'):
            invoice = self.invoice
            current_state = SPONSOR_STATE_INVOICED
            if invoice.invoice_ok:
                current_state = SPONSOR_STATE_CHECKED
                if invoice.partial_payment:
                    current_state = SPONSOR_STATE_PARTIALLY_PAID
                if invoice.complete_payment:
                    current_state = SPONSOR_STATE_COMPLETELY_PAID

        return current_state

    class Meta:
        unique_together = ('sponsorcategory', 'sponsor')
        permissions = (
            (CAN_CLOSE_SPONSORING_CODENAME, _('puede cerrar patrocinio')),
        )
        ordering = ['sponsor__organization_name']


@reversion.register
class Sponsor(SaveReversionMixin, AuditUserTime):
    """Represents a sponsor. The active atributte is like a soft deletion."""

    RESPONSABLE_INSCRIPTO = 'responsable inscripto'
    MONOTRIBUTO = 'monotributo'
    CONSUMIDOR_FINAL = 'consumidor final'
    EXTERIOR = 'exterior'
    OTRO = 'otro'
    RESPONSABLE_NO_INSCRIPTO = 'responsable no inscripto'
    IVA_NO_RESPONSABLE = 'iva no responsable'
    IVA_SUJETO_EXENTO = 'iva sujeto exento'
    SUJETO_NO_CATEGORIZADO = 'sujeto no categorizado'
    IVA_LIBERADO = 'iva liberado'

website/events/helpers/views.py
from django.db.models import Q
import functools
import operator


def search_filtered_queryset(base_queryset, search_fields, search_value):
    filters = []
    for key, value in search_fields.items():
        field_filter = key
        if value != 'equal':
            field_filter = field_filter + '__' + value
        filter_dict = {field_filter: search_value}
        filters.append(Q(**filter_dict))
    queryset = base_queryset.filter(functools.reduce(operator.or_, filters))
    return queryset

website/events/templates/providers/provider_detail.html
{% extends "events_base.html" %}
{% load static %}
{% block content %}
<div class="container">
    {% block route-navigator %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><i class="fas fa-home"></i><a href="{% url 'events_home' %}"> Inicio</a></li>
            <li class="breadcrumb-item"><i class="fas fa-dolly"></i><a href="{% url 'provider_list' %}"> Proveedores</a></li>
            {% if form.instance.pk %}
            <li class="breadcrumb-item"><a href="{% url 'sponsor_detail' pk=form.instance.pk %}"><i class="fas fa-dolly-flatbed"></i> {{provider.organization_name}}</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="#">Edición</a></li>
            {% else %}
            <li class="breadcrumb-item" aria-current="page"><i class="fas fa-dolly-flatbed"></i> {{provider.organization_name}}</li>
            {% endif %}
        </ol>
    </nav>
    {% endblock %}

    <div class="row provider-detail">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h3>Datos del proveedor </h3>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th scope="row">Nombre/Razón social</th>
                        <td>{{ provider.organization_name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Banco</th>
                        <td>{{ provider.bank_entity }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Tipo Cuenta</th>
                        <td>{{ provider.get_account_type_display }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Número Cuenta</th>
                        <td>{{ provider.account_number }}</td>
                    </tr>
                    <tr>
                        <th scope="row">CBU</th>
                        <td>{{ provider.cbu }}</td>
                    </tr>
                    <tr>
                        <th scope="row">CUIT</th>
                        <td>{{ provider.document_number }}</td>
                    </tr>
                </tbody>
            </table>
            {% if perms.events.change_provider %}
            <a class="btn btn-primary col-2 float-right mx-1" href="{% url 'provider_change' provider.pk %}"><i class="fas fa-pencil-alt"></i> Editar</a>
            {% endif %}
            <a class="btn btn-danger col-2 float-right mx-1" href="{% url 'provider_list' %}"><i class="fas fa-undo"></i> Volver</a>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}

website/events/templates/providers/provider_form.html
{% extends "events_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    {% block route-navigator %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><i class="fas fa-home"></i><a href="{% url 'events_home' %}"> Inicio</a></li>
          <li class="breadcrumb-item"><i class="fas fa-dolly"></i><a href="{% url 'provider_list' %}"> Proveedores</a></li>
          {% if form.instance.pk %}
        <li class="breadcrumb-item"><i class="fas fa-dolly-flatbed"></i> <a href="{% url 'sponsor_detail' pk=form.instance.pk %}">{{form.instance.organization_name}}</a></li>
        <li class="breadcrumb-item" aria-current="page"><i class="fas fa-edit"></i> Edición</li>
        {% else %}
        <li class="breadcrumb-item" aria-current="page"><i class="fas fa-certificate"></i> Crear</li>
        {% endif %}
        </ol>
    </nav>
    {% endblock %}

    <form method="POST">
        {% csrf_token %}
        {% crispy form %}
        <button type="submit" class="btn btn-success col-2 float-right mx-1">
            <i class="fas fa-save"></i> 
            {% if form.instance.pk %}
            Actualizar
            {% else %}
            Crear
            {% endif %}
        </button>
        <a class="btn btn-danger col-2 float-right mx-1" href="{% url 'provider_list' %}"><i class="fas fa-undo"></i> Volver</a>
</div>
{% endblock %}

website/events/templates/providers/providers_list.html
{% extends "events_base_paginated_list.html" %}

{% block route-navigator %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><i class="fas fa-home"></i><a href="{% url 'events_home' %}"> Inicio</a></li>
      <li class="breadcrumb-item" aria-current="page"><i class="fas fa-dolly"></i> Proveedores</li>
    </ol>
</nav>
{% endblock %}

{% block list_title %}
<h1>Proveedores</h1>
{%endblock%}

{% block list_content %}
    <div class="row sponsors-list">
        <div class="col-md-12">
            <table class="table table-striped row-clickeable-table">
                <thead>
                    <tr>
                        <th scope="row">Nombre/Razón social</th>
                        <th scope="row">CUIT</th>
                        <th scope="row">Banco</th>
                        <th scope="row">Tipo Cuenta</th>
                    </tr>
                </thead>
                <tbody>
                {% for provider in provider_list %}
                    <tr onclick="window.location='{% url 'provider_detail' pk=provider.pk %}';" class="clikeable">
                        <td >{{ provider.organization_name }}</td>
                        <td>{{ provider.document_number }}</td>
                        <td> {{ provider.bank_entity}}</td>
                        <td> {{ provider.get_account_type_display}}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="100%" class="empty-list">
                            <strong>No hay proveedores activos.</strong>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row sponsors-list-actions">
        <div class="col-md-12 text-right">
            {% if perms.events.add_provider %}
            <a class="btn btn-primary col-2 float-right mx-1" href="{% url 'provider_create' %}"><i class="fas fa-certificate"></i> Crear</a>
            {% endif %}
            <a class="btn btn-danger col-2 float-right mx-1" href="{% url 'events_home' %}"><i class="fas fa-undo"></i> Volver</a>
        </div>
    </div>
{% endblock %}